---
- import_tasks: install_packages.yml

- name: create c3nav dir
  file:
    path: /opt/c3nav
    state: directory
    owner: root
    group: root
    mode: 0775

- name: add c3nav user
  user:
    name: c3nav
    system: true
    createhome: false
    home: /opt/c3nav

- name: clone c3nav repo
  git:
    repo: https://github.com/johanvdw/c3nav.git
    version: fosdem_2020
    dest: /opt/c3nav

- name: create c3nav data dir
  file:
    path: /opt/c3nav/data
    state: directory
    owner: c3nav
    group: c3nav
    mode: 0775

- name: create c3nav media dir
  file:
    path: /opt/c3nav/data/media
    state: directory
    owner: c3nav
    group: c3nav
    mode: 0775

- import_tasks: virtualenv.yml

- name: create configuration dir
  file:
    path: /etc/c3nav
    state: directory
    owner: root
    group: root
    mode: 0775

- name: create log dir
  file:
    path: /var/log/c3nav
    state: directory
    owner: c3nav
    group: c3nav
    mode: 0775

- name: copy configuration file
  template:
    src: c3nav/c3nav.cfg
    dest: /etc/c3nav/c3nav.cfg
    owner: root
    mode: 0644
    force: false

- name: copy logo
  copy:
    src: media/logo.png
    dest: /opt/c3nav/data/media/logo.png
    owner: root
    mode: 0644

- include: configure_celery.yml
- include: configure_gunicorn.yml
- include: configure_nginx.yml
