- name: restart sreview-web
  service:
    name: sreview-web
    state: restarted
  when: '"encoder-master" in group_names'

- name: restart sreview-dispatch
  service:
    name: sreview-dispatch
    state: restarted
  when: '"encoder-master" in group_names'
