- name: restart sreview-web
  service:
    name: sreview-web
    state: restarted
  when: '"encoder-master" in group_names'

- name: restart sreview-dispatch
  service:
    name: sreview-dispatch
    state: restarted
  when: '"encoder-master" in group_names'

- name: restart execd
  service:
    name: gridengine-exec
    enabled: true
    state: restarted
  ignore_errors: true
