---
- name: fix the hosts file so gridengine (and other things) will work
  template:
    dest: /etc/hosts
    src: hosts.j2
    owner: root
    group: root
    mode: 0664
  notify:
    - restart execd

- name: install load script
  copy:
    src: load.sh
    dest: /usr/local/bin/load.sh
    mode: 0755
  notify:
    - restart execd

- name: ensure reviewmaster is active qmaster
  copy:
    src: act_qmaster
    dest: /var/lib/gridengine/default/common/act_qmaster
    owner: sgeadmin
    group: sgeadmin
  notify:
    - restart execd
