- import_tasks: configure_network.yml
- import_tasks: install_packages.yml
- import_tasks: cgroup_setup.yml
- import_tasks: install_signal-status.yml
- import_tasks: install_extra_hw.yml
- import_tasks: install_video-status.yml
- import_tasks: install_video-streamer.yml
