$ANSIBLE_VAULT;1.1;AES256
66623966346566353061336239386564356161313230613935316366396639633632366632346362
6163373835316562666334333538303266323164313731300a333764386430663165633135623566
61613736646632643036363666326662333736363262336638363630353466653538366438396663
6137656462633666650a373138653636303732633630396462393262313733313931313136343035
64326132323939336538366430346439643234613032323239666638373235636365373336666633
34313836326538353335343035383064666333303039656531636564623565356138333462393763
31376462346233653130376531363964393761623838353934306539663033313334373230303564
61326534376530366563343362343635333834373232316331613938306637663538653165346666
33666365313033383766383761373633653839303631633765376666323261376536333331636233
65346366623065313833666430616537646437326537646537313861656439326131303464626231
39663038363661356332396665666131356331373466356363383034376539333266376634343862
61666438643335646334656666343733643233643135363136363666646130336266323331323036
30636535376331636134313035356666613437326436376266376530653639393362316263323535
32616231343639366230326133326266313165373333386166383462343933396666336162643961
323930393036643265636464363765326535
