---
- name: install ffmpeg from backports
  apt:
    state: latest
    install_recommends: false
    default_release: "{{ ansible_distribution_release }}-backports"
    package:
    - ffmpeg

- name: install receiver script
  template:
    src: video-streamer/video-receiver.sh
    dest: /usr/local/bin/video-receiver.sh
    owner: root
    group: root
    mode: 0755

- name: install video-recorder script
  template:
    src: video-streamer/video-recorder.sh
    dest: /usr/local/bin/video-recorder.sh
    owner: root
    group: root
    mode: 0755

- name: install video-usbreset.py script
  copy:
    src: video-streamer/video-usbreset.py
    dest: /usr/local/bin/video-usbreset.py
    owner: root
    group: root
    mode: 0755


- name: install video-receiver service
  template:
    src: video-streamer/video-receiver.service
    dest: /etc/systemd/system/video-receiver.service
    owner: root
    group: root
    mode: 0644
  register: videoreceiver

- name: create recording directory
  file:
    path: "/home/video-recording"
    state: directory
    mode: 0755

- name: install video-recorder service
  template:
    src: video-streamer/video-recorder.service
    dest: /etc/systemd/system/video-recorder.service
    owner: root
    group: root
    mode: 0644
  register: videorecorder

- name: perform a daemon-reload if any service has been modified
  systemd:
    daemon_reload: true
  when: videoreceiver.changed or videorecorder.changed

- name: enable video-receiver service
  service:
    name: video-receiver
    enabled: true
    state: started

# - name: disable video-streamer service
#   service:
#     name: video-streamer
#     enabled: false
#     state: stopped

# video-recorder IS NOT enabled by default/from ansible!
# do not add it here.
# vk 2017-01-28

- name: restart service if video-receiver.service has been modified
  service:
    name: video-receiver
    state: restarted
  when: videoreceiver.changed

- name: enable video-receiver service
  systemd:
    name: video-receiver
    enabled: true
    state: started
    daemon_reload: true
