---
collections:
  - name: prometheus.prometheus
    source: https://github.com/prometheus-community/ansible
    type: git
roles:
  - name: caddy_ansible.caddy_ansible
  - name: fosdem.bind
    src: https://github.com/FOSDEM/ansible-bind.git
    type: git
  - name: paulfantom.restic
    src: https://github.com/paulfantom/ansible-restic.git
    type: git
  - name: rsyslog
    src: https://github.com/Oefenweb/ansible-rsyslog.git
    type: git
