- name: install to-pretalx.pl
  template:
    src: to-pretalx.pl
    dest: /usr/local/bin/to-pretalx.pl
    mode: 0755

- name: install reply-to-brokens
  template:
    src: reply-to-brokens
    dest: /var/lib/sreview/reply-to-brokens
    mode: 0755
